/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#444748",
        "on-error-container": "#ffdad6",
        "primary": "#c6c6c7",
        "surface-container-high": "#2a2a2a",
        "secondary": "#ffb3b0",
        "surface-variant": "#353534",
        "surface-container": "#201f1f",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed-variant": "#930019",
        "on-tertiary": "#032f64",
        "secondary-fixed-dim": "#ffb3b0",
        "secondary-container": "#bf0124",
        "on-tertiary-fixed": "#001b3f",
        "on-primary-fixed-variant": "#454747",
        "on-tertiary-fixed-variant": "#24467c",
        "on-primary-container": "#7f8181",
        "primary-container": "#151718",
        "inverse-surface": "#e5e2e1",
        "surface-tint": "#c6c6c7",
        "surface": "#131313",
        "primary-fixed": "#e2e2e2",
        "tertiary": "#abc7ff",
        "error": "#ffb4ab",
        "on-primary": "#2f3131",
        "background": "#131313",
        "on-secondary-fixed": "#410006",
        "inverse-on-surface": "#313030",
        "surface-bright": "#3a3939",
        "error-container": "#93000a",
        "tertiary-fixed": "#d7e2ff",
        "surface-dim": "#131313",
        "on-error": "#690005",
        "surface-container-highest": "#353534",
        "surface-container-low": "#1c1b1b",
        "on-secondary": "#68000f",
        "secondary-fixed": "#ffdad8",
        "outline": "#8e9192",
        "inverse-primary": "#5d5f5f",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed-dim": "#abc7ff",
        "on-primary-fixed": "#1a1c1c",
        "primary-fixed-dim": "#c6c6c7",
        "on-background": "#e5e2e1",
        "tertiary-container": "#001637",
        "on-tertiary-container": "#6181ba",
        "on-surface-variant": "#c4c7c7",
        "on-secondary-container": "#ffcdca"
      },
      fontFamily: {
        inter: ["Inter"],
      },
    },
  },
  plugins: [],
};
